GoalSetTracker/GoalSetTracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from login import views as login_views
from goal import views as goal_views
from commentary import views as comment_views
from upload import views as upload_views
from notifications import views as notif_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^goal/(?P<goal_id>[0-9]+)/upload/', upload_views.archivo_list,
        name='list_uploads'),
    url(r'^goal/(?P<goal_id>[0-9]+)/subgoal/(?P<subgoal_id>[0-9]+)/upload/',
        upload_views.archivo_list, name='list_sub_uploads'),
    url(r'^goal/(?P<goal_id>[0-9]+)/editar/(?P<id_archivo>\d+)/$',
        upload_views.archivo_editar, name='edit_upload'),
    url(r'^goal/(?P<goal_id>[0-9]+)/subgoal/(?P<subgoal_id>[0-9]+)/'
        r'editar/(?P<id_archivo>\d+)/$',
        upload_views.archivo_editar, name='edit_sub_upload'),
    url(r'^goal/(?P<goal_id>[0-9]+)/remove_upload/(?P<id_archivo>\d+)/$',
        upload_views.archivo_eliminar, name='remove_upload'),
    url(r'^goal/(?P<goal_id>[0-9]+)/subgoal/(?P<subgoal_id>[0-9]+)/'
        r'remove_upload/(?P<id_archivo>\d+)/$',
        upload_views.archivo_eliminar, name='remove_sub_upload'),
    url(r'^goal/(?P<goal_id>[0-9]+)/add_file/', upload_views.upload_img,
        name='add_file'),
    url(r'^goal/(?P<goal_id>[0-9]+)/subgoal/(?P<subgoal_id>[0-9]+)/add_file/',
        upload_views.upload_img, name='add_sub_file'),
    url(r'^login/', include('login.urls')),
    url(r'^$', login_views.login, name='login'),
    url(r'^logout$', login_views.logout, name='logout'),
    url(r'^new_user$', login_views.new_user, name='new_user'),
    url(r'^home/(?P<username>[\w.@+-]+)/$', login_views.home, name='home'),
    url(r'^home/$', login_views.home, name='home'),
    url(r'^new_goal$', goal_views.new_goal, name='new_goal'),

    # Goal
    url(r'^goal/(?P<goal_id>[0-9]+)/$', goal_views.detail_goal, name='detail'),
    url(r'^goal/(?P<goal_id>[0-9]+)/delete$', goal_views.delete_goal,
        name='delete_goal'),
    url(r'^goal/(?P<goal_id>[0-9]+)/modify$', goal_views.modify_goal,
        name='modify_goal'),
    # Goal - comments
    url(r'^goal/(?P<goal_id>[0-9]+)/new_comment$', comment_views.new_comment,
        name='new_comment'),
    url(r'^goal/(?P<goal_id>[0-9]+)/modify_comment/(?P<comment_id>[0-9]+)/$',
        comment_views.modify_comment, name='modify_comment'),
    url(r'^goal/(?P<goal_id>[0-9]+)/delete_comment/(?P<comment_id>[0-9]+)/$',
        comment_views.delete_comment, name='delete_comment'),

    # Sub goal
    url(r'^goal/(?P<goal_id>[0-9]+)/new_sub_goal$', goal_views.new_sub_goal,
        name='new_sub_goal'),
    url(r'^goal/(?P<goal_id>[0-9]+)/subgoal/(?P<subgoal_id>[0-9]+)$',
        goal_views.detail_sub_goal, name='detail_sub_goal'),
    url(r'^goal/(?P<goal_id>[0-9]+)/subgoal/(?P<subgoal_id>[0-9]+)/modify$',
        goal_views.modify_sub_goal, name='modify_sub_goal'),
    # Sub goal - comments
    url(r'^goal/(?P<goal_id>[0-9]+)/subgoal/'
        r'(?P<subgoal_id>[0-9]+)/new_comment$',
        comment_views.new_comment, name='new_comment'),
    url(r'^goal/(?P<goal_id>[0-9]+)/subgoal/(?P<subgoal_id>[0-9]+)/'
        r'modify_comment/(?P<comment_id>[0-9]+)/$',
        comment_views.modify_comment, name='modify_comment'),
    url(r'^goal/(?P<goal_id>[0-9]+)/subgoal/(?P<subgoal_id>[0-9]+)/'
        r'delete_comment/(?P<comment_id>[0-9]+)/$',
        comment_views.delete_comment, name='delete_comment'),
    url(r'^category/', include('category.urls')),
    url(r'^admin/', admin.site.urls),
    # Allauth URLS
    url(r'^accounts/', include('allauth.urls')),
    url(r'^{}(?P<path>.*)$'.format(settings.MEDIA_URL[1:]),
        upload_views.protected_serve, {'file_root': settings.MEDIA_ROOT}),
    url(r'^$', RedirectView.as_view(url='/upload/media/', permanent=True)),
    # Notifications
    url(r'^notifications/$', notif_views.show_goals_near_deadline,
        name='show_notifications'),
    url(r'^notifications/goal_exist_near_deadline/$',
        notif_views.goal_exist_near_deadline,
        name='goal_exist_near_deadline'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GoalSetTracker/login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # /login
    url(r'^$', views.login, name='login'),
]

GoalSetTracker/goal/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User

TipePriority = (
    ('H', 'High'),
    ('M', 'Medium'),
    ('L', 'Low'),
)

TipeState = (
    ('PROGRESS', 'In Progress'),
    ('PROPOS', 'Proposed'),
    ('FINISH', 'Finished'),
)


@python_2_unicode_compatible
class AbstractGoal(models.Model):
    goal_text = models.CharField(max_length=200)
    finish_date = models.DateTimeField('finish date')
    create_date = models.DateTimeField('date published')
    priority = models.CharField(max_length=1, choices=TipePriority)
    state = models.CharField(max_length=1, choices=TipeState)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.goal_text

    def is_active(self):
        return (self.state != "FINISH")
    
    def time_until_deadline(self):
        return (self.finish_date - timezone.now())
    
    def near_deadline(self):       
        near_deadline_days = 7
        days = self.time_until_deadline().days
        return (days < near_deadline_days)


@python_2_unicode_compatible
class Goal(AbstractGoal):
    categoria = models.CharField(max_length=200)

    def __str__(self):
        return self.categoria


@python_2_unicode_compatible
class SubGoal(AbstractGoal):
    sub_goal_text = models.CharField(max_length=200)
    goal_father = models.ForeignKey(Goal, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.sub_goal_text

GoalSetTracker/goal/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from login.views import redirect_home
from .models import Goal, SubGoal
from commentary.models import Comment


def new_goal(request):
    if request.user.is_authenticated:
        try:
            user = User.objects.get(username=request.user.username)
        except Exception as e:
            return HttpResponse("El usuario no existe")
        if request.method == "POST":
            finish_date = request.POST.get("finish_date")
            if finish_date == '':
                finish_date = timezone.now()
            goal = Goal.objects.create(goal_text=request.POST.get("goal_text"),
                                       finish_date=finish_date,
                                       create_date=timezone.now(),
                                       priority=request.POST.get("priority"),
                                       state=request.POST.get("state"),
                                       owner=user
                                       )
            goal.save()
            return redirect_home(request.user.username)
        else:
            return render(request, 'goal/new_goal.html')
    else:
        return HttpResponseRedirect("/login")


def new_sub_goal(request, goal_id):
    goal = get_object_or_404(Goal, pk=goal_id)
    if request.user.is_authenticated:
        if request.method == "POST":
            finish_date = request.POST.get("finish_date")
            if finish_date == '':
                finish_date = timezone.now()
            if request.user == goal.owner:
                subgoal = SubGoal.objects.create(
                                        goal_text=request.POST
                                                         .get("goal_text"),
                                        finish_date=finish_date,
                                        create_date=timezone.now(),
                                        priority=request.POST.get("priority"),
                                        state=request.POST.get("state"),
                                        owner=request.user,
                                        goal_father=goal
                                        )
            return redirect_goal(goal_id)
        else:
            return render(request, 'goal/new_sub_goal.html', {'goal': goal})
    else:
        return HttpResponseRedirect("/login")


def delete_goal(request, goal_id):
    goal = get_object_or_404(Goal, pk=goal_id)
    if request.user.is_authenticated:
        if request.user == goal.owner:
            if request.method == "POST":
                goal.delete()
                return redirect_home(request.user.username)
            else:
                return render(request, 'goal/delete.html', {'goal': goal})
    else:
        return HttpResponseRedirect("/login")


def detail_goal(request, goal_id):
    if request.user.is_authenticated:
        goal = get_object_or_404(Goal, pk=goal_id)
        if request.user == goal.owner:
            comments = (Comment.objects.all().filter(goal=goal)
                               .order_by('-create_date'))
            return render(request, 'goal/detail.html',
                          {'goal': goal, 'comments': comments})
    return redirect_home(request.user)


def detail_sub_goal(request, goal_id, subgoal_id):
    if request.user.is_authenticated:
        goal = get_object_or_404(Goal, pk=goal_id)
        if request.user == goal.owner:
            subgoal = get_object_or_404(SubGoal, pk=subgoal_id)
            comments = (Comment.objects.all().filter(goal=subgoal_id)
                                             .order_by('-create_date'))
            return render(request, 'goal/detail_sub_goal.html',
                          {'goal': goal, 'subgoal': subgoal,
                           'comments': comments})
    return redirect_home(request.user)


def modify_goal(request, goal_id):
    goal = get_object_or_404(Goal, pk=goal_id)
    if request.user.is_authenticated:
        if request.user == goal.owner:
            if request.method == "POST":
                if request.POST.get("finish_date"):
                    goal.finish_date = request.POST.get("finish_date")
                if request.POST.get("goal_text"):
                    goal.goal_text = request.POST.get("goal_text")
                if request.POST.get("create_date"):
                    goal.create_date = request.POST.get("create_date")
                if request.POST.get("priority"):
                    goal.priority = request.POST.get("priority")
                if request.POST.get("state"):
                    goal.state = request.POST.get("state")
                goal.save()
                return redirect_goal(goal_id)
            else:
                return render(request, 'goal/modify_goal.html', {'goal': goal})


def modify_sub_goal(request, goal_id, subgoal_id):
    subgoal = get_object_or_404(SubGoal, pk=subgoal_id)
    goal = get_object_or_404(Goal, pk=goal_id)
    # TODO chequear que son del usuario las metas y submetas
    if request.user.is_authenticated:
        if request.user == goal.owner:
            if request.method == "POST":
                if request.POST.get("finish_date"):
                    subgoal.finish_date = request.POST.get("finish_date")
                if request.POST.get("goal_text"):
                    subgoal.goal_text = request.POST.get("goal_text")
                if request.POST.get("create_date"):
                    subgoal.create_date = request.POST.get("create_date")
                if request.POST.get("priority"):
                    subgoal.priority = request.POST.get("priority")
                if request.POST.get("state"):
                    subgoal.state = request.POST.get("state")
                subgoal.save()
                return redirect_goal(goal_id, subgoal_id)
            else:
                return render(request, 'goal/modify_sub_goal.html',
                              {'goal': goal, 'subgoal': subgoal})


def redirect_goal(id, subgoal_id=None):
    if subgoal_id:
        return HttpResponseRedirect("/goal/{}/subgoal/{}"
                                    .format(id, subgoal_id))
    else:
        return HttpResponseRedirect("/goal/{}".format(id))

GoalSetTracker/goal/templates/goal/delete.html
{% extends 'login/base.html' %}

{% block content %}
<h1>{{ goal.goal_text }}</h1>

<h3><span style="color:red">Are You sure that you want to delete this Goal?</span></h3>
<form action="{% url 'delete_goal' goal.id %}" method="post">{% csrf_token %}
    <input type="submit" value="Delete Goal" />
</form>
{% endblock %}

GoalSetTracker/goal/templates/goal/detail.html
{% extends 'login/base.html' %}

{% block content %}
<h1>{{ goal.goal_text }}</h1>
<h3>Finish Date: {{ goal.finish_date }}</h3>
<h3>Create Date: {{ goal.create_date }}</h3>
<h3>Priority {{ goal.priority }}</h3>
<h3>State {{ goal.state }}</h3>
<ul>
{% for subgoal in goal.subgoal_set.all %}
    <li><a href="{% url 'detail_sub_goal' goal.id subgoal.id%}" name=>{{ subgoal.goal_text }}</a></li>
{% endfor %}
</ul>
<h4>New Sub Goal</h4>
<form action="{% url 'new_sub_goal' goal.id %}" method="get">
    <input type="submit" value="New Sub Goal" />
</form>
<h4>Modify Goal</h4>
<form action="{% url 'modify_goal' goal.id %}" method="get">
    <input type="submit" value="Modify Goal" />
</form>
<h4>Delete Goal</h4>
<form action="{% url 'delete_goal' goal.id %}" method="get">
    <input type="submit" value="Delete Goal" />
</form>

<h4>Make a Comment</h4>
<form action="{% url 'new_comment' goal.id %}" method="get">
    <input type="submit" value="New Comment" />
</form>
<br />

<h4>Comments</h4>
<div class="comment list" style="background-color:white; width:40%;
                                    border-radius:3px">
{% for comment in comments %}
    <div class="comment" style="border: 1px solid #777777; border-radius: 5px;
                                 padding: 0px 0px 0px 10px; margin:10px 0px;">
    <p>{{ comment.text }}</p>
    <span class="comment-subtext" style="font-size: 11px;">
    {{ comment.owner }} - {{ comment.create_date }}
    <br />
    <div class="comment-edit-delete" >
    <a href="{% url 'modify_comment' goal.id comment.id %}" style="text-decoration: none !important;">[edit]</a>
    <a href="{% url 'delete_comment' goal.id comment.id %}" onclick="return confirm('Are you sure you want to delete the comment?')"
       style="text-decoration: none !important;">[delete]</a>
    </div>
    </span>
    </div>
{% endfor %}

</div>
<br />

<h4>Files</h4>
<form action="{% url 'list_uploads' goal.id %}" method="get">
    <input type="submit" value="File List" />
</form>
<form action="{% url 'add_file' goal.id %}" method="get">
    <input type="submit" value="Add File" />
</form>
<br />

<form action="{% url 'home' %}" method="get">
    <input type="submit" value="Back to homepage" />
</form>
{% endblock %}

GoalSetTracker/goal/templates/goal/detail_sub_goal.html
{% extends 'login/base.html' %}

{% block content %}
<h1>{{ subgoal.goal_text }}</h1>
<h3>Finish Date: {{ subgoal.finish_date }}</h3>
<h3>Create Date: {{ subgoal.create_date }}</h3>
<h3>Priority {{ subgoal.priority }}</h3>
<h3>State {{ subgoal.state }}</h3>

<h4>Modify Goal</h4>
<form action="{% url 'modify_sub_goal' goal.id subgoal.id %}" method="get">
    <input type="submit" value="Modify Goal" />
</form>


<h4>Make a Comment</h4>
<form action="{% url 'new_comment' goal.id subgoal.id %}" method="get">
    <input type="submit" value="New Comment" />
</form>
<br />

<h4>Comments</h4>
<div class="comment list" style="background-color:white; width:40%;
                                    border-radius:3px">
{% for comment in comments %}
    <div class="comment" style="border: 1px solid #777777; border-radius: 5px;
                                 padding: 0px 0px 0px 10px; margin:10px 0px;">
    <p>{{ comment.text }}</p>
    <span class="comment-subtext" style="font-size: 11px;">
    {{ comment.owner }} - {{ comment.create_date }}
    <br />
    <div class="comment-edit-delete" >
    <a href="{% url 'modify_comment' goal.id subgoal.id comment.id %}" style="text-decoration: none !important;">[edit]</a>
    <a href="{% url 'delete_comment' goal.id subgoal.id comment.id %}" onclick="return confirm('Are you sure you want to delete the comment?')"
       style="text-decoration: none !important;">[delete]</a>
    </div>
    </span>
    </div>
{% endfor %}

</div>
<h4>Files</h4>
<form action="{% url 'list_sub_uploads' goal.id subgoal.id  %}" method="get">
    <input type="submit" value="File List" />
</form>
<form action="{% url 'add_sub_file' goal.id subgoal.id  %}" method="get">
    <input type="submit" value="Add File" />
</form>
<br />
{% endblock %}

GoalSetTracker/goal/templates/goal/modify_goal.html
{% extends 'login/base.html' %}

{% block content %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title> Modify Goal </title>
</head>
    <h1> Modify Goal: {{goal.goal_text}}</h1>
  <body>
    <form action="{% url 'modify_goal' goal.id %}" method="post">{% csrf_token %}
      <p> Description <input name="goal_text" size=40 value="{{ goal.goal_text }}"> </p>
      <p> Deadline <input name="finish_date" size=40 type="date" value="{{ goal.finish_date| date:"Y-m-d"}}"></p>
      <p> Priority
      <input type="radio" name="priority" value="H" > High
      <input type="radio" name="priority" value="M"checked> Medium
      <input type="radio" name="priority" value="L"> Low  </p>
      <p> State
      <input type="radio" name="state" value="PROGRESS" checked> In Progress
      <input type="radio" name="state" value="PROPOS"> Proposed
      <input type="radio" name="state" value="FINISH"> Finished </p>
      <p> <input type="submit" value="Submit"> </p
    </form>
  </body>
</html>
{% endblock %}

GoalSetTracker/goal/templates/goal/modify_sub_goal.html
{% extends 'login/base.html' %}

{% block content %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title> Modify Sub Goal </title>
</head>
    <h1> Modify Sub Goal: {{subgoal.goal_text}}</h1>
  <body>
    <form action="{% url 'modify_sub_goal' goal.id subgoal.id%}" method="post">{% csrf_token %}
      <p> Description <input name="goal_text" size=40 value="{{ subgoal.goal_text }}"> </p>
      <p> Deadline <input name="finish_date" size=40 type="date" value="{{ subgoal.finish_date| date:"Y-m-d"}}"> </p>
      <p> Priority
      <input type="radio" name="priority" value="H" > High
      <input type="radio" name="priority" value="M"checked> Medium
      <input type="radio" name="priority" value="L"> Low  </p>
      <p> State
      <input type="radio" name="state" value="PROGRESS" checked> In Progress
      <input type="radio" name="state" value="PROPOS"> Proposed
      <input type="radio" name="state" value="FINISH"> Finished </p>
      <p> <input type="submit" value="Submit"> </p
    </form>
  </body>
</html>
{% endblock %}

GoalSetTracker/goal/templates/goal/new_goal.html
{% extends 'login/base.html' %}

{% block content %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title> New Goal </title>
</head>
    <h1> New Goal </h1>
  <body>
    <form action="{% url 'new_goal' %}" method="post">{% csrf_token %}
      <p> Description <input name="goal_text" size=40 required> </p>
      <p> Deadline <input name="finish_date" size=40 type="date"> </p>
      <p> Priority
      <input type="radio" name="priority" value="H" > High
      <input type="radio" name="priority" value="M"checked> Medium
      <input type="radio" name="priority" value="L"> Low  </p>
      <p> State
      <input type="radio" name="state" value="PROGRESS" checked> In Progress
      <input type="radio" name="state" value="PROPOS"> Proposed
      <input type="radio" name="state" value="FINISH"> Finished </p>
      <p> <input type="submit" value="Submit"> </p
    </form>
  </body>
</html>
{% endblock %}

GoalSetTracker/goal/templates/goal/new_sub_goal.html
{% extends 'login/base.html' %}

{% block content %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title> New Sub Goal </title>
</head>
    <h1> New Sub Goal </h1>
    <h1> Original Goal : {{goal.goal_text}} </h1>
  <body>
    <form action="{% url 'new_sub_goal' goal.id %}" method="post">{% csrf_token %}
      <p> Description <input name="goal_text" size=40 required> </p>
      <p> Deadline <input name="finish_date" size=40 type="date"> </p>
      <p> Priority
      <input type="radio" name="priority" value="H" > High
      <input type="radio" name="priority" value="M"checked> Medium
      <input type="radio" name="priority" value="L"> Low  </p>
      <p> State
      <input type="radio" name="state" value="PROGRESS" checked> In Progress
      <input type="radio" name="state" value="PROPOS"> Proposed
      <input type="radio" name="state" value="FINISH"> Finished </p>
      <p> <input type="submit" value="Submit"> </p
    </form>

  </body>
</html>
{% endblock %}